import type { Metadata } from "next";
import Navbar from "../../components/shared/navbar";
import { SidebarProvider, SidebarTrigger } from "../../components/ui/sidebar";
import { AppSidebar } from "../../components/shared/app-sidebar";
import Sidebar from "../../components/shared/sidebar";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="">
      <Navbar />
      <main className="flex">
        <Sidebar />
        {children}
      </main>
    </div>
  );
}
