import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Register",
  description: "Generated by create next app",
};

export default function RegisterLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="">{children}</div>;
}
